### ISSUE TITLE
Changing text color

### ISSUE THREAD

**Issue by solusmart** [nkl-kst/MMM-OnThisDay#11]
I'm not sure how in the .css or .js files or in the MagicMirror/css/custom.css file I can change the text color from grey to #FFFFFFF

The only thing I've found is in MMM-OnThisDay.css at line 36, but only for links

``
    color: inherit !important;
``

Edit: would be a great add in the config file options ;)

**Comment by nkl-kst** [comment]
You could do something like this in your `MagicMirror/css/custom.css`: `.MMM-OnThisDay {color: #fff}`. This should work, because the module uses `color: inherit`. Let me know if this works for you.

**Comment by solusmart** [comment]
It did work, thank you!

**Comment by nkl-kst** [comment]
Perfect, glad to help.
