### ISSUE TITLE
Only shows date in header

### ISSUE THREAD

**Issue by JoshuaShelswell** [nkl-kst/MMM-OnThisDay#12]
Doesnt show On this day in....

**Comment by nkl-kst** [comment]
Could you please provide some more informations? What language are you using? What is exactly shown and what do you expect? Thanks.

**Comment by JoshuaShelswell** [comment]
English and i thought for sure this application used to say "On this day on..." then the date but i could be mistaken lol

**Comment by nkl-kst** [comment]
This module just takes the title from Wikipedia (https://en.wikipedia.org/wiki/Main_Page in your case) and prints it as the header. Feel free to open a PR to improve it with this feature. You could also try to use a custom function in your module config in the header property.

**Comment by JoshuaShelswell** [comment]
oh i see, thank you!
