### ISSUE TITLE
Cant use this module with other modules

### ISSUE THREAD

**Issue by JoshuaShelswell** [nkl-kst/MMM-OnThisDay#15]
I cant put this module with anything else on the entire side of the screen because there is no limit on how many things it pulls from wiki or height limit, taking up the whole screen, not sure how to fix this, setting the height doesnt help, ive been making other apps smaller and smaller but it doesnt matter

![image](https://user-images.githubusercontent.com/61985684/103164034-1374e980-47d4-11eb-9615-d667f2b73840.png)

**Comment by nkl-kst** [comment]
There is already a feature request to control the number of displayed items, see #9. I will work on this as soon as possible. You could also create a working PR for this feature, thanks.
