### ISSUE TITLE
Truncate title/header length using maxWidth?

### ISSUE THREAD

**Issue by smithbill17** [nkl-kst/MMM-OnThisDay#16]
Can the title/header be truncated in length with the 'maxWidth' config option?

Whenever the title/header is very long, it causes the rest of the OnThisDay event information to be pushed left across the screen (see attached image on my phone).
![Screenshot_20210201-075848289](https://user-images.githubusercontent.com/66825587/106430571-e87d5580-6463-11eb-8be4-5ed29e4eb054.jpg)

**Comment by nkl-kst** [comment]
Hi smithbill,

thanks for opening this issue. Yep that's ugly, I'll look at this as soon as possible. The header should not overflow the configured `maxWidth`.

**Comment by smithbill17** [comment]
In the meantime, is there some .CSS file somewhere that we can make a dirty edit to in order to stop this ugly title length thing? The ludicrously long title seems to happen every other day now which kind of makes this module unusable at the minute.

**Comment by Mikklo** [comment]
Ran in to the same issue today, if anyone else has this problem, the solution in the PR works, just add 
```
.MMM-OnThisDay {
    width: 400px;
}
```
to MMM-OnThisDay.css
