### ISSUE TITLE
No data available

### ISSUE THREAD

**Issue by Munror96** [nkl-kst/MMM-OnThisDay#17]
When running mirror the module displays "no data available", not sure why, any help is appreciated.
Config -
`        {
            module: 'MMM-OnThisDay',
            position: "bottom_right", 
            config: {
            }
        },`

![Screenshot_20210315-013531_VNC Viewer](https://user-images.githubusercontent.com/80656975/111093190-3049cf00-8530-11eb-8dd9-119d8568f573.jpg)

**Comment by nkl-kst** [comment]
Hi, thanks for opening this issue. Which language setting are you using in your mirror config?

**Comment by Munror96** [comment]
Thanks for the quick reply, I am using English in my mirror config

**Comment by dand3l10n** [comment]
> When running mirror the module displays "no data available", not sure why, any help is appreciated.
> Config -
> ` { module: 'MMM-OnThisDay', position: "bottom_right", config: { } },`
> 
> ![Screenshot_20210315-013531_VNC Viewer](https://user-images.githubusercontent.com/80656975/111093190-3049cf00-8530-11eb-8dd9-119d8568f573.jpg)

Same problem..

**Comment by nkl-kst** [comment]
> 
> 
> Thanks for the quick reply, I am using English in my mirror config

Sorry for the late response. When starting your mirror with this module enabled, there should be some log output like

```
MMM-OnThisDay starting...
Using language <YOUR_LANGUAGE_HERE>.
```

Do you see these logs? Which language do you see here?

Could you please try another language in your `config.js`, like `language: 'de'`.

**Comment by RyanScottLewis** [comment]
I had this issue until I restarted my server (running without Electron).

Also to note is this message is displayed while downloading and parsing. On a fast machine, it might not even be seen but on a RasPi Zero, it's there for quite awhile.

**Comment by theishman** [comment]
Getting the same. Here's what I see in the log

> DISPLAY="${DISPLAY:=:0}" ./node_modules/.bin/electron js/electron.js

[15.10.2021 16:05.48.183] [LOG]   Starting MagicMirror: v2.16.0
[15.10.2021 16:05.48.188] [LOG]   Loading config ...
[15.10.2021 16:05.48.199] [LOG]   Loading module helpers ...
[15.10.2021 16:05.51.227] [LOG]   Initializing new module helper ...
[15.10.2021 16:05.51.228] [LOG]   Module helper loaded: MMM-OnThisDay
[15.10.2021 16:05.51.229] [LOG]   All module helpers loaded.
[15.10.2021 16:05.51.375] [LOG]   Starting server on port 8080 ...
[15.10.2021 16:05.51.398] [LOG]   Server started ...
[15.10.2021 16:05.51.399] [LOG]   Connecting socket for: MMM-OnThisDay
[15.10.2021 16:05.51.400] [LOG]   Starting module helper: MMM-OnThisDay
[15.10.2021 16:05.51.400] [LOG]   Sockets connected & modules started ...
[15.10.2021 16:05.52.781] [LOG]   Launching application.
[15.10.2021 16:05.54.726] [LOG]   MMM-OnThisDay: Received socket notification LOAD_EVENTS.
[15.10.2021 16:05.54.728] [LOG]   MMM-OnThisDay: Load events ...
[15.10.2021 16:05.54.979] [ERROR] Whoops! There was an uncaught exception...
[15.10.2021 16:05.54.984] [ERROR] Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket._finishInit (_tls_wrap.js:936:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
  code: 'CERT_HAS_EXPIRED'

**Comment by jackmeyer** [comment]
Same here, CERT_HAS_EXPIRED

**Comment by KopiTubruk** [comment]
Hi,

is there any solution for this issue?

**Comment by nkl-kst** [comment]
I don't think the error is related to this plugin. `CERT_HAS_EXPIRED` indicates there is a certificate problem that should be solved. Maybe your system root certificates are outdated? You could try to `wget` your wiki site and see if the problem exists there too.

**Comment by jeremyMagicMirror** [comment]
Has anyone figured out how to fix this issue? I attempted to re-download all certificates, but that did not work.The only Issue I could force it coming from was that I got some warnings when running 'npm install --only=prod' with a deprecated warning relating to "native performance.now() and performance.timeOrigin, as well as a two optional dependencies. Please let me know if additional information is needed or if there is anyway that you know how to solve this. Any help possible is very much appreciated!!! Thank you guys so much!!

**Comment by jeremyMagicMirror** [comment]
here is what I am seeing:
npm WARN deprecated [w3c-hr-time@1.0.2](mailto:w3c-hr-time@1.0.2): Use your platform's native performance.now() and performance.timeOrigin.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: [fsevents@~2.3.1](mailto:fsevents@~2.3.1) (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for [fsevents@2.3.2](mailto:fsevents@2.3.2): wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

**Comment by nipper2000h** [comment]
Did anyone figure out a resolution to this issue? I too am seeing  CERT_HAS_EXPIRED in my logs.

**Comment by KristjanESPERANTO** [comment]
I cannot provoke the error in my system. The module works perfectly with languages 'de' and 'en'.

I use the following versions:
- MagicMirror²: 2.25.0
- node: 21.1.0
- npm: 10.2.2
- MMM-OnThisDay: 0.1.1

**Comment by nkl-kst** [comment]
Closing, since this issue doesn't seem to be related to the module.
