### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by chassain** [nkl-kst/MMM-OnThisDay#2]
Hello,

thanks for this magic module.. i dream to have the same with a french translation...may be a day...have a good day

**Comment by nkl-kst** [comment]
Thanks for your issue. I would like to support as much languages as possible.

Currently the module uses these Wikipedia RSS feeds to get the data:

English: https://en.wikipedia.org/w/api.php?action=featuredfeed&feed=onthisday&feedformat=atom
German: https://de.wikipedia.org/w/api.php?action=featuredfeed&feed=onthisday&feedformat=atom

But I didn't found a french equivalent to this. Any idea of a french feed?

**Comment by chassain** [comment]
Hello,

I'm using MMM Widget and this feed : https://www.france-pittoresque.com/spip.php?page=ephemeride
Maybe you can integrate this for your module (for french)

**Comment by chassain** [comment]
i found this https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal and see "Éphéméride du 24 juillet" on right

**Comment by nkl-kst** [comment]
> i found this https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Accueil_principal and see "Éphéméride du 24 juillet" on right

I will have a look at this one. Maybe it is possible to use similar sites for the other languages, because I don't like to write different parsers for every supported language :)

**Comment by chassain** [comment]
I understand. The other feed is just for me..thanks again for your work

**Comment by nkl-kst** [comment]
I think a simple solution could be to use the Wikipedia main site of each language and define a unique CSS selector where to find the list of events on the language specific page. To support a new language only the specific CSS selector for that language is needed.

**Comment by chassain** [comment]
it's a good solution. i m going to see but i m a beginner (medium maybe) and i m not sure the place of the list of events is always the same each day

**Comment by nkl-kst** [comment]
I implemented the mentioned solution in branch `support_more_languages`. Do you have time to try it out on your mirror?

**Comment by chassain** [comment]
Yes. No problem. I will check tomorrow.  Thanks

**Comment by chassain** [comment]
Hello.
No change. It always in english

**Comment by chassain** [comment]
It's simply a great job..no data in first because i didn't have copy all files ...thanks again.very thanks for this nice module

**Comment by nkl-kst** [comment]
Glad to hear it worked and thanks for your reply. I will fix the tests and merge it into master branch as soon as possible.

-------- Ursprüngliche Nachricht --------Von: chassain <notifications@github.com> Datum: 27.07.20  19:01  (GMT+01:00) An: nkl-kst/MMM-OnThisDay <MMM-OnThisDay@noreply.github.com> Cc: Nikolai Keist <louis6708@gmail.com>, Comment <comment@noreply.github.com> Betreff: Re: [nkl-kst/MMM-OnThisDay] French translation (#2) 
It's simply a great job..no data in first because i didn't have copy all files ...thanks again.very thanks for this nice module

**Comment by nkl-kst** [comment]
Glad to hear it worked and thanks for your reply. I will fix the tests and merge it into master branch as soon as possible.
