### ISSUE TITLE
endpoint error

### ISSUE THREAD

**Issue by godsyn** [nkl-kst/MMM-OnThisDay#25]
`    apiBase: "http://on-this-day-api.herokuapp.com",`
`error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail`

API endpoint seems down.

**Comment by nkl-kst** [comment]
This module doesn't use this API.

**Comment by godsyn** [comment]
You are correct. I posted this to the wrong location. My apologies.
