### ISSUE TITLE
npm deprecated dependencies

### ISSUE THREAD

**Issue by KSumwalt** [nkl-kst/MMM-OnThisDay#8]
I receive the following when I do the Install the Dependencies step, `npm install --only=prod`

`npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
`

This is on a newly setup Raspberry Pi 4, on a fresh SD Card set up August 2, 2020.  I did a copy and paste to compete the install.  Magic Mirror 2 is running fine and does show the module.

Kindest Regards,
Karl

**Comment by nkl-kst** [comment]
Hi Karl,
thanks for this issue. Deprecation warnings shouldn't be a problem during installation. Could you please show your config and logs for further investigation? Thanks.Cheers

**Comment by KSumwalt** [comment]
Thank you for the reply and information, Nikolai.  At first I thought the plugin was not working but did edit my post when I realized I needed to make a setting from another plugin, MMM-ProfileSwitcher in order to allow this one to show.  My apologies for any confusion.  So I am up and running and all seems fine.  I can supply the config and logs if you still desire them.

My Best
Karl

**Comment by nkl-kst** [comment]
Thanks for the clarification, glad to hear it works now. I'm closing this issue for now.
